Add volto-slate-label components
eea/volto-slate-label pull request #1
Opened 2022-03-28 11:52 UTC by nileshgulia1

## Edit mode:
<img width="1057" alt="Screenshot 2022-03-28 at 5 17 51 PM" src="https://user-images.githubusercontent.com/22280901/160391847-bd8e5922-11af-4d9d-8e4b-f0f3b451805c.png">

<img width="383" alt="Screenshot 2022-03-28 at 5 20 45 PM" src="https://user-images.githubusercontent.com/22280901/160392079-462a866f-3a36-4b33-9eb1-1175165decc0.png">

## View:
<img width="1057" alt="Screenshot 2022-03-28 at 5 18 09 PM" src="https://user-images.githubusercontent.com/22280901/160391880-2f2b61b9-f0e0-434f-8ea5-3e1858fe0c2a.png">

2022-03-28 11:54 UTC, nileshgulia1 commented on src/editor/styles.less
> +.ui.popup.high {
@avoinea How about making these styles configurable? For now these are taken from https://github.com/eea/volto-eea-design-system/blob/develop/theme/themes/eea/elements/label.overrides#L10

2022-03-29 13:18 UTC, avoinea commented
![no-type](https://user-images.githubusercontent.com/323385/160619977-16e9f47e-8219-4cf6-9946-23796e573d96.png)

@nileshgulia1 
I not type is selected, the popup is white background with white text on it. You should default one of the options.

2022-03-29 13:24 UTC, avoinea commented
@nileshgulia1 You should also add another switch for `Always open` in the sense that the tooltip box should be closed by default and appear when you click on the selected text. If `Always open` is `true` then the tooltip should stay always opened. The text in tooltip box should be `richtext` (we should be able to add links and sub sup formating CO₂, etc.)

2022-03-29 13:38 UTC, avoinea requested changes

2022-03-29 13:38 UTC, avoinea commented on src/editor/index.js
> +import mentainanceSVG from '@plone/volto/icons/maintenance.svg';
...and `comment.svg` :smile:

2022-03-29 13:38 UTC, avoinea commented on src/editor/index.js
> +import mentainanceSVG from '@plone/volto/icons/maintenance.svg';
See https://pastanaga.io/icons/

2022-03-29 15:05 UTC, nileshgulia1 commented on src/editor/index.js
> +import mentainanceSVG from '@plone/volto/icons/maintenance.svg';
> Can you try `annotation.svg` icon.

mm.. I too want `annotation` 😭 https://github.com/plone/volto/issues/3207#issuecomment-1081790665

2022-04-04 13:09 UTC, avoinea approved these changes

2022-04-04 13:23 UTC, merged